import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Playfair_Display,
  Lora,
  DM_Serif_Text,
  Noto_Sans_Mongolian,
} from "next/font/google";
import "./globals.css";
import { Header } from "@/components/us/Header";
import { Toaster } from "sonner";
import SnowEffect from "@/components/effects/SnowEffect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-times-new-roman",
  subsets: ["latin"],
});

const dmSerifText = DM_Serif_Text({
  weight: "400",
  variable: "--font-dm-serif-text",
  subsets: ["latin"],
});

const notoSansMongolian = Noto_Sans_Mongolian({
  weight: "400",
  variable: "--font-noto-sans-mongolian",
  subsets: ["mongolian"],
});

export const metadata: Metadata = {
  title: "Event Lux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${lora.variable} ${dmSerifText.variable} ${notoSansMongolian.variable} antialiased bg-black`}
      >
        <SnowEffect />
        <header className=" fixed top-0 left-0 right-0 z-1000">
          <Header />
        </header>
        {children}

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
